### ISSUE TITLE
Explain how to use AutoDoc in packages that already use GAPDoc

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#101]
Explain how to use AutoDoc in packages that already use GAPDoc, in more detail than Section 1.3.
- [x] a minimal example how to use `AutoDoc()` to compile your existing GAPDoc manual, nothing else. 
- [x] some examples showing the `gapdoc` options.
- [x] an explanation how to use `AutoDoc()` to generate a title page for use in a GAPDoc based manual (nothing else)
- [ ] examples for the fancier `scaffold` options
- [ ] finally, how to mix you GAPDoc manual with additional AutoDoc-style documentation comments.

This is motivated by #100

**Comment by sebasguts** [comment]
The last item ''How to mix a GAPDoc manual with AutoDoc'' is already there, just hidden in 1.2. Should this be more prominent?

**Comment by fingolfin** [comment]
I think this is pretty OK now, compared to when I wrote this issue originall. In any case, this is not concrete enough to be helpful. If somebody (including me) is unhappy with some aspects of the manual, they should either write a specific criticism for the current version of the manual, or submit a PR.
