### ISSUE TITLE
Add examples for using AutoDoc()

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#102]
Add examples for using `AutoDoc()` to the manual.

See issue #100.

**Comment by sebasguts** [comment]
There already is the tutorial chapter. Should we collect the examples from there with a suitable description?

**Comment by fingolfin** [comment]
I think we can close this now. Of course there are more variants that could be explained, but I'd rather wait to see if somebody ever asks for advice with any of them, then work with them to improve the manual.
