### ISSUE TITLE
Regression if index is empty

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#106]
Commit a912844ccfd08796a0a83f95c63b8b64e07cb092 causes a regressions where various package manuals fail to compile: Namely, if they contain an empty index.

So that possibly explains why that fake index entry was added ;-).

The proper solution would be to *not* emit `<TheIndex/>` if there is nothing in the index. However, I am not quite sure whether can do that. After all, there might be `<Index>` elements just aboy anywhere.

Note that if I patch GAPDoc, modifying `AddPageNumbersToSix` to check if `pos=fail`, and if so, skip that case, everything seems to work fine -- except that there is an empty index. Which should be fine, since this case should only occur for new manuals, where there simply is no index data yet.

An alternative workaround would be modify the `GAPDoc2LaTeXProcs.Tail` variable -- the code in it finalizes the `.pnr` file. Well, we could simply modify it to always append an entry for the index, i.e. by prepending this command to `GAPDoc2LaTeXProcs.Tail`:
```
"\\immediate\\write\\pagenrlog{[\"Ind\", 0, 0], \\arabic{page},}\n",
```
Since GAPDoc uses `Position` to search through the list in the pnr file, any real entry for the index chapter would come before this fake one; thus the fake one should only have any effect if there really is no index.

Thoughts?

**Comment by sebasguts** [comment]
In my oppinion, GAPDoc should be patched here. By typing ```<TheIndex/>``` I claim that I want an index, whether it is empty or not.

Since one can already set ```index``` to false, one can already turn it of explicitly. Implicitly turning it off when the list is empty would probably break some xml inserted in the manual, as you already said. So I think I would vote for the ```GAPDoc2LaTeXProcs.Tail``` solution you suggested, although it is quite hacky :).

**Comment by fingolfin** [comment]
Yeah, I am already typing a mail to Frank. But in the meantime, I think we should also add a workaround, because we don't know when a GAPDoc update might be released.

**Comment by sebasguts** [comment]
I will insert the line you suggested.
