### ISSUE TITLE
@BeginCode seems to remove leading whitespace, making it useless

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#110]
I just tried to use @BeginCode, but all indention in my code was lost. That makes it useless :-(.

For now, I think I'll go back to writing GAPDoc-XML directly -- .autodoc files have too many problems. :-(

**Comment by fingolfin** [comment]
For the record, this is what I was trying:
```
@Chapter Combining &AutoDoc; and &GAPDoc;

bla

@Section Building an existing &GAPDoc; manual using &AutoDoc;

bla

@BeginCode c1
LoadPackage( "GAPDoc" );
MakeGAPDocDoc( "doc", "manual", [ "../PackageInfo.g" ],
               "FooBar", "../../..", "MathJax");; 
CopyHTMLStyleFiles( "doc" );
GAPDocManualLab( "FooBar" );; 
@EndCode
@InsertCode c1
```

**Comment by sebasguts** [comment]
That is actually strange. Investigating.

**Comment by sebasguts** [comment]
Found the problem, its here: https://github.com/gap-packages/AutoDoc/blob/master/gap/Parser.gi#L631 . I am currently not sure how to get rid of this.

**Comment by fingolfin** [comment]
Can't you just skip that command if `plain_text_mode` is true?

**Comment by sebasguts** [comment]
Nope, that wasn't the error after all. The problem is the printing function at the moment. Code nodes in the documentation tree are just plain text nodes, which means their output gets normalized. I will introduce a different kind of node.
