### ISSUE TITLE
Remove "QUIT" from makedoc.g

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#112]
I am tempted to remove the "QUIT" from the end of our `makedoc.g`. 

Thing is, the only thing it does is to make `gap makedoc.g` a convenient command. But `gap < makedoc.g` is similarly convenient, and many projects also allow `make doc`.

On the other hand, it makes it impossible to use `makedoc.g` from other GAP scripts without spawning a fresh GAP interpreter. This is why my release tools ends up starting 4 or 5 GAP processes -- if `makedoc.g` did not QUIT (and also `update.g` from GitHubPageForGAP), I think I could get this down to one or two.

But perhaps I am missing reasons why the QUIT really is a good idea... Thoughts?

**Comment by sebasguts** [comment]
The ```QUIT;``` is there for the reasons you mentioned, i.e., to make sure GAP terminates after the ```gap makedoc.g``` call, no matter if there are errors or not. We can change it, if you want to. I will just have to make sure that every script using is converted to ```gap < makedoc.g```, but that is okay.

**Comment by oysteins** [comment]
One possible disadvantage of redirecting input from a file is that GAP then behaves as if running interactively, and prints out the results of all top-level expressions.  Whether this is a problem or not depends on whether one cares about what is printed on standard output.  In this particular case it is probably not very important.

However, it's often bothering me that there seems to be no good way to run a GAP file as a script, the way one can in most other similar languages: `python foo.py` does what I would expect, `gap foo.g` does not.  Adding `QUIT;` to the end of the file makes `gap foo.g` work, but then (as was mentioned above) the file cannot be read from a GAP session.

The best one can do is maybe to pipe `Read("foo.g");` into GAP.  I tried writing a shell script which does this:

```bash
#!/bin/bash
if [ "$#" -ne 1 ]
then
    echo 'Usage: rungapfile FILE'
    exit 1
fi
file=$1
if [ -e $file ]
then
    echo 'Read("'$1'");' | gap -q
else
    echo "Error: file $file does not exist"
    exit 1
fi
```

If this code is placed in an executable file `rungapfile` in `$PATH`, one can say

```
$ rungapfile foo.g
```

to run a GAP file.  No extra output, no need to write `QUIT;` at the end of the file.

**Comment by fingolfin** [comment]
The QUIT was actually removed some time ago (unaware of this long-forgotten issue... :/).
