### ISSUE TITLE
Alternative to maketest?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#114]
So @alex-konovalov pointed out to me that his packages (e.g. wedderga) use the following approach towards manual examples: Similar our `maketest` code, he implemented a function which extracts manual examples, and makes them easy to run.
But his approach is to turn the manual examples into `tst/*.tst` files, whose names is based on the chapters they are from. The tests then are run like any other test, assuming your package runs all `tst/*.tst` files anyway. Here is the function he uses for that:

``` gap
ExtractMyManualExamples:=function( pkgname, main, files )
local path, tst, i, s, name, output, ch, a;
path:=Directory( 
        Concatenation(PackageInfo(pkgname)[1].InstallationPath, "/doc") );
Print("Extracting manual examples for ", pkgname, " package ...\n" );
tst:=ExtractExamples( path, main, files, "Chapter" );
Print(Length(tst), " chapters detected\n");
for i in [ 1 .. Length(tst) ] do 
  Print( "Chapter ", i, " : \c" );
  if Length( tst[i] ) > 0 then
    s := String(i);
    if Length(s)=1 then 
      # works for <100 chapters
      s:=Concatenation("0",s); 
    fi;
    name := Filename( 
              Directory( 
                Concatenation( PackageInfo(pkgname)[1].InstallationPath, 
                               "/tst" ) ), 
                Concatenation( LowercaseString(pkgname), s, ".tst" ) );
    output := OutputTextFile( name, false ); # to empty the file first
    SetPrintFormattingStatus( output, false ); # to avoid line breaks
    ch := tst[i];
    AppendTo(output, "# ", pkgname, ", chapter ",i,"\n");
    for a in ch do
      AppendTo(output, "\n# ",a[2], a[1]);
    od;
    Print("extracted ", Length(ch), " examples \n");
  else
    Print("no examples \n" );    
  fi;  
od;
end;
```

It would be easy to integrate this into `AutoDoc`, with some slight changes (e.g. instead of a package name, it should take a package info record).

I wonder whether we should do something similar -- either in addition to `maketest`, or as a replacement? I wonder what the pros and cons of each approach are? Perhaps creating one tst file per chapter makes it easier to track down where a problem sits, exactly?

@sebasguts BTW, can you point me to any projects using the maketest feature, so that I can try it and learn how ti works, exactly?

**Comment by alex-konovalov** [comment]
In main GAP manuals, there is a convention that if you run examples within each chapter in the same order, they should run 100% identically. I use the same "per chapter" approach in my packages, even though the test may run all tests in the same GAP session, unlike GAP's `make testmanuals`.

**Comment by fingolfin** [comment]
Sure, but this is also achieved by our `maketest.g`, which basically is a wrapper around GAPDoc's `RunExamples` command. The nice side effect of that is that `RunExamples` tell you the exact location *in the XML file* where a test failure occurred.

**Comment by alex-konovalov** [comment]
Yes, in my case I have an extra redirection, since the test output points to the place in the test file, and the example in the test file points to the original location in the *.xml file or in the code. That's not too bad, though, since I have test files which I can run separately with `Test`, I can comment out or modify examples there to experiment with them, I can easily send them to collaborators. This is why I would prefer to generate actual test files rather than test examples "on the fly".

**Comment by alex-konovalov** [comment]
BTW, my script to extract examples is also available at Gist [here](https://gist.github.com/alex-konovalov/693df56eadd3f5b74d39)
