### ISSUE TITLE
Markdown-lists don't work properly in chunks

### ISSUE THREAD

**Issue by markusbaumeister** [gap-packages/AutoDoc#141]
Consider the following code:
```
#! @BeginChunk List
#! * Lorem ipsum dolor sit amet, consetetur sadipscing elitr, 
#!   sed diam nonumy eirmod tempor invidunt ut labore et 
#!   dolore magna aliquyam erat, sed diam voluptua.
#! * At vero eos et accusam et justo duo dolores et ea rebum. 
#!   Stet clita kasd gubergren, no sea takimata sanctus est 
#!   Lorem ipsum dolor sit amet.
#! @EndChunk
```
```
#! @InsertChunk List
```
This will result in a broken list (only the lines that have a * will be part of a list). Usually AutoDoc recognizes that the next lines are still part of the list and formats correctly.

If you don't manually wrap the lines, it works. Using the GAPDoc-syntax
```
<List>
  <Item>bla</Item>
</List>
```
also works fine.

**Comment by sebasguts** [comment]
I cannot reproduce this bug. I get a well formated list with chunks and without.

**Comment by sebasguts** [comment]
I cannot reproduce this bug. I get a well formated list with chunks and without.

**Comment by markusbaumeister** [comment]
I just tried to include my code in the AutoDoc-documentation. As you said, it worked fine there. It still does not work in my documentation. As far as I can see it is not an option problem, as they are:
AutoDoc( rec( scaffold := rec(
                    MainPage := false
                    ),
);

**Comment by sebasguts** [comment]
To clarify this issue: This happens if the chunk is inserted twice.
