### ISSUE TITLE
<Example> in <ManSection> does not work

### ISSUE THREAD

**Issue by markusbaumeister** [gap-packages/AutoDoc#144]
The following code throws an error (although it is valid GAPDoc-code):
```
#! <ManSection>
#!   <Filt Name="TestExample" Arg=""/>
#!   <Description>
#! <Example>
#! gap&gt; 1 + 2;
#! 3
#! </Example>
#!  </Description>
#! </ManSection>
```
This is relevant, since it is sometimes necessary to escape into GAPDoc-syntax, for example in documenting synonyms (which can't be easily classified).

**Comment by sebasguts** [comment]
I tested the example, and it is displayed nicely in both pdf and html files. Can you please attach the error message?

**Comment by sebasguts** [comment]
Please note that if you do this, you need to have a `@Chapter` and an `@Section` open, since `ManItem`s are basically subsections.

**Comment by markusbaumeister** [comment]
I forgot about @Chapter and @Section which led me to messing up my minimal example. Sorry about that :(.
The original problem appeared because of an empty line in the example environment:
```
#! <ManSection>
#!   <Filt Name="TestExample" Arg=""/>
#!   <Description>
#! <Example>
#! gap&gt; 1 + 2;
#! 3
#! 
#! gap&gt; 2;
#! 2
#! </Example>
#!  </Description>
#! </ManSection>
```
and gives the error message
```
#I Checking XML structure . . .
XML Parse Error: Line 5045 Character 1
-----------
<Example>
^
-----------
Wrong element in Example: P
!!! Type 'Show();' to watch the input string in pager - starting with
    line containing error !!!
Error,  called from
ParseError( str, r.start, Concatenation( "Wrong element in ", name, ": ", r.content[Position( l, false )].name ) ); at /opt/gap4r8/pkg/GAPDoc/lib/GAPDoc.gi:99 called from
CheckAndCleanGapDocTree( x, str ) at /opt/gap4r8/pkg/GAPDoc/lib/GAPDoc.gi:157 called from
func( elm ) at /opt/gap4r8/lib/coll.gi:1613 called from
ForAll( r.content, function ( x )
      return CheckAndCleanGapDocTree( x, str );
  end ) at /opt/gap4r8/pkg/GAPDoc/lib/GAPDoc.gi:157 called from
CheckAndCleanGapDocTree( x, str ) at /opt/gap4r8/pkg/GAPDoc/lib/GAPDoc.gi:157 called from
...  at line 414 of makedoc.g
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```
This is not an issue in GAPDoc.

**Comment by sebasguts** [comment]
Yep. AutoDoc now replaces empty lines with a `<P/>` tag. This is what is happening here. You could
* Use AutoDoc's `@ExampleSession` environment
* Remove the empty line
* Make it two example session environments

**Comment by sebasguts** [comment]
I am not sure this is something we are ever going to fix, actually, since it can be avoided very easily and is probably very hard to fix properly (altough not impossible). I will leave it open for now anyway.

**Comment by markusbaumeister** [comment]
Using  @ExampleSession works but removes colouring of example.

**Comment by sebasguts** [comment]
Not with the latest version.

**Comment by sebasguts** [comment]
Also, you can use `>` instead of `&gt;`.

**Comment by markusbaumeister** [comment]
In my version @ExampleSession still removes the colouring if inside an <Example>-environment.

**Comment by sebasguts** [comment]
You have to replace the `<Example` tag by `@ExampleSession` completely.

**Comment by markusbaumeister** [comment]
```
#! <ManSection>
#!   <Filt Name="TestExample" Arg=""/>
#!   <Description>
#! @ExampleSession
#! gap&gt; 1 + 2;
#! 3
#! 
#! gap&gt; 2;
#! 2
#! @EndExampleSession
#!  </Description>
#! </ManSection>
```
has no colours (with the current version of AutoDoc).

**Comment by sebasguts** [comment]
This one has:
```
#! <ManSection>
#!   <Filt Name="TestExample" Arg=""/>
#!   <Description>
#! @ExampleSession
#! gap> 1 + 2;
#! 3
#! 
#! gap> 2;
#! 2
#! @EndExampleSession
#!  </Description>
#! </ManSection>
```
Apparently because AutoDoc adds `CDATA` tags around the GAP code, and you didn't. I don't know how it should be done, but the above example works.

**Comment by fingolfin** [comment]
@markusbaumeister @sebasguts so, is this resolved and can be closed? If not, what precisely is the remaining issue?

**Comment by fingolfin** [comment]
I am closing this as I believe, based on what I read here, that it's been resolved; if that's wrong, please feel free to reopen.

**Comment by sebasguts** [comment]
No, this is resolved by adding `@ExampleSession`
