### ISSUE TITLE
Update CHANGES file

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#148]
The CHANGES files hasn't been upgraded recently. It is it the only way for a regular user to learn about new features, or to find out when something was added, so it would be good to add the missing items back, and keep it up-to-date in future releases.

**Comment by sebasguts** [comment]
Sounds like a good plan. Could you review/merge PR's #146 and #147 first? Afterwards, I will update the changes file :).

**Comment by fingolfin** [comment]
I have now update the CHANGES file, purely based on commit message titles, so I might have missed some stuff -- so please, if you find the time, check the CHANGES file once more, then we can close this issue.
