### ISSUE TITLE
Move gapdoc_latex_options to gapdoc record

### ISSUE THREAD

**Issue by sebasguts** [gap-packages/AutoDoc#149]
and rename it to `GAPDocLaTeXOptions`. Then mark `gapdoc_latex_options` as deprecated and provide an example for `GAPDocLaTeXOptions`.

**Comment by fingolfin** [comment]
This should be fairly straightforward. As you (implicitly suggest), we should of course keep supporting `gapdoc_latex_options` for a time as an alias. But we can also be proactive and submit PRs to the handful packages that use `gapdoc_latex_options`. Here's a quick list:
- [ ] ArangoDBInterface
- [ ] intpic
- [ ] FactInt
- [ ] groupoids
- [ ] numericalsgps
- [ ] sgpviz
- [ ] xmodalg
- [ ] xmog

**Comment by cdwensley** [comment]
If GAPDocLaTeXOptions is going to be introduced it would be convenient if it were to happen soon so that it can be used in new releases of groupoids and xmod.

**Comment by fingolfin** [comment]
Patches are welcome :-)

**Comment by cdwensley** [comment]
OK - I've forked the repository and will have a go, without quite knowing what's required. 
The benefit to me will be that at the end of the day I'll get a tutorial on git squash etc.
