### ISSUE TITLE
Index much shorter in PDF than in HTML

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/AutoDoc#153]
I've compared https://gap-packages.github.io/AutoDoc/doc/chapInd.html with the PDF from GAP 4.9.0 release. Both report version 2017.09.08.

**Comment by fingolfin** [comment]
Which index? The one in the AutoDoc manual? That's due to the @ in identifiers, and was resolved in https://github.com/frankluebeck/GAPDoc/commit/7205d87fa6b064c9c5d113172288fd3c8427047c so hopefully will be OK in the next GAPDoc release

**Comment by alex-konovalov** [comment]
Yes, the one in the AutoDoc manual.

**Comment by fingolfin** [comment]
This was fixed in GAPDoc 1.6.2
