### ISSUE TITLE
A few suggestions for the AutoDoc manual

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/AutoDoc#157]
- [x] 2.1.8 `@ChapterInfo`:
    GAPDoc's `<A>` element is intended only for arguments.
    In the given example, `p` and `G` and `ordtbl` do not occur as
    arguments, they could be marked with `<M>` or `<C>` elements.

- [x] 2.2.3 `@EndSection`:
    The text suggests that putting text "between sections" of a chapter
    makes sense.
    I would recommend that a chapter might have some introductory text
    before the first section starts (so this text belongs to the chapter
    but not to a section), but nothing should appear between sections.

- [x] 2.2.5 `@EndSubsection`:
    See the above comment on `@EndSection`.

- [x] 2.2.7 `@EndAutoDoc`:
    Write "effect" not "affect"?

- [x] 2.2.10 `@Level`:
    Write "about levels" not "about groups"?

- [x] 2.2.13 `@BeginExampleSession and @EndExampleSession`:
    Write "GAP prompt" instead of "gap prompt"?
    (Alternatively, one could write "`gap> `" prompt,
    but there is also the partial prompt "`> `".)

- [ ] 2.2.14 `@BeginLog and @EndLog`:
    References to the GAPDoc manual could be made more specific,
    and could appear as links.

- [x] 2.3 `Title page commands`:
    Write "from <F>PackageInfo.g</F>" and
    "do not have a <F>PackageInfo.g</F> file to extract".

**Comment by fingolfin** [comment]
Unfortunately we (well, at least I) had completely forgotten about this issue. I now addressed some of the points listed here in PR #204 (and marked them in the issue description).

**Comment by fingolfin** [comment]
I also mostly agree with @oysteins analysis and suggestions. However, I'd keep `@EndSection` and `@ @EndSubsection` around for backwards compatibility, I'd just change them to (a) print a fat warning, and (b) probably they should do nothing.

This fits in very well with the Markdown spirit, too, where we might use `# Chapter`, `## Section` and `### Subsection` to start the various things, but there is no way to "end" them other than to start a new chapter/section/subsections/

**Comment by fingolfin** [comment]
@sebasguts any additional thoughts or comments?

**Comment by fingolfin** [comment]
I just filed issue #206 which should take care of the EndSection and EndSubsection remarks. This leaves the remark on @BeginLog and @EndLog where we should indeed consider adding explicit links to the GAPDoc manual (actually, this would be nice in other places, too)
