### ISSUE TITLE
AutoDocWorksheet() does not succeed with absolute dir option

### ISSUE THREAD

**Issue by gwhitney** [gap-packages/AutoDoc#165]
As far as I can tell, at the moment AutoDocWorksheet() never succeeds if the options record contains a dir entry whose value is an IsDirectory() object consisting of an absolute path. Instead, it generates an error as follows:
```
gap> LoadPackage("AutoDoc");
─────────────────────────────────────────────────────────────────────────────
Loading  AutoDoc 2018.02.14 (Generate documentation from GAP source code)
by Sebastian Gutsche (http://wwwb.math.rwth-aachen.de/~gutsche/) and
   Max Horn (http://www.quendi.de/math).
Homepage: https://gap-packages.github.io/AutoDoc
─────────────────────────────────────────────────────────────────────────────
true
gap> tmpdir := DirectoryTemporary();;
gap> AutoDocWorksheet( "tst/worksheet.tst", rec( dir := tmpdir ) );
Generating documentation in Directory("/tmp/tm1UYs8b/")
Error, Variable: 'doc_dir_rel' must have an assigned value in
  tmp := Number( Filename( doc_dir_rel, "" ), function ( x )
        return x = '/';
    end )
 ; at [...]/gap-4.9.2/pkg/AutoDoc-2018.02.14/gap/Magic.gi:359 called from 
AutoDoc( "AutoDocWorksheet", arg[2] 
 ); at [...]/gap-4.9.2/pkg/AutoDoc-2018.02.14/gap/AutoDocMainFunction.gi:374 called from
<function "AutoDocWorksheet">( <arguments> )
```

I will momentarily submit a pull request with a proposed solution to this problem.

**Comment by fingolfin** [comment]
A general problem with worksheets is that they are essentially undocumented (and I complained to @sebasguts about this before). So I have a hard time evaluating what is "right" or "expected" from them. From the manual, it's not even clear to me how to invoke `AutoDocWorksheet` correctly, and what the input should; I can't even tell if the invocation you give above (resp. in your pull request) makes sense.

I hope @sebasguts can chime in a bit...

**Comment by gwhitney** [comment]
Well, for what it is worth, what I took away from the manual is that an AutoDocWorksheet() call should be exactly like an AutoDoc call, except the "package" argument is replaced by one or more explicit filenames. (And no PackageInfo.g file is scanned.) That to me is reasonably well-defined and logically consistent, and it is the goal toward which my changes have been working. If it does not seem to be the most useful/reasonable behavior for AutoDocWorksheet(), please let me know and I am happy to adjust. In any case, this issue is actually completely orthogonal to the question of AutoDocWorksheet() vs. AutoDoc(); neither one currently works with an absolute directory, and it would be very useful to get them to do so. I was simply using AutoDocWorksheet() for testing purposes, as it is easier to build a test harness around. It is also possible to test this issue with AutoDoc(), please let me know if you would like me to change the testing of this to use AutoDoc(), and then we can add AutoDocWorksheet() tests as the intended behavior becomes settled. (Personally I think the intended behavior is reasonably well-defined already, but I absolutely defer to the experts' judgment.)
