### ISSUE TITLE
Deprecate @BeginSystem, @EndSystem, and @InsertSystem

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#205]
I could not find any packages using `@BeginSystem` or `@EndSystem`, so I think we could just remove those two right away.

For `@InsertSystem`, I found several (meta) packages using it:
- [x] ArangoDBInterface
- [x] ToricVarieties
- [x] GroupRepresentationsForCAP
- [x] homalg_project_extensions/Blocks
- [x] homalg_project_extensions/SingularForHomalg
- [x] homalg_project_extensions/PrimaryDecomposition
- [x] homalg_project_extensions/LessGenerators

So, all of these are from Siegen, so I am hopefully we can get them to accept PRs that change `@InsertSystem` to `@InsertChunk`. Once that's done, and there were releases, we can remove `@InsertSystem`, too.

**Comment by sebasguts** [comment]
Will provide some PR's

**Comment by fingolfin** [comment]
Thanks. It'd be great if you could edit the text above and insert links to those PRs, that'll help us track the status of this.

**Comment by fingolfin** [comment]
I've now provided those PR instead, and most of them have been merged, only waiting for https://github.com/homalg-project/SingularForHomalg/pull/2 but I am hopeful @mohamed-barakat will merge it soon. I guess we then still should wait a bit with releasing a new version that removes these chunks... In the meantime, I'll prepare a PR to print out a warning when they are used.

**Comment by mohamed-barakat** [comment]
@fingolfin: Merged, thanks.

**Comment by sebasguts** [comment]
Ah sorry, totally forgot about this.

Are we sufficiently sure nobody else uses those commands? Well, I guess we cannot take care of code that is not available somewhere.

**Comment by fingolfin** [comment]
Resolved by deprecating (instead of removing) these commands; deprecation here means that a warning is printed in red.
We can perform the actual removal at some day in the future (say with GAP 4.12 or 4.13), or simply leave these in for ever (but perhaps remove them from the manual at some point).
