### ISSUE TITLE
problem with the option extract_examples

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/AutoDoc#240]
The function `AUTODOC_ExtractMyManualExamples` should first remove all testfiles whose name follows the scheme of the files it creates.
Currently it can happen that outdated testfiles remain --this happens when the number of those chapters decreases for which manual examples exist.

**Comment by fingolfin** [comment]
That's a very good point. I guess right now the pattern would be `tst/pkgname*.tst`. That might also lead it to delete things it shouldn't? Safer would be to always put the extracted manual examples into a subdirectory, say `tst/manual_examples`, then one could simply remove everything in that directory... But this would of course break compatibility...

**Comment by zickgraf** [comment]
> I guess right now the pattern would be tst/pkgname*.tst. That might also lead it to delete things it shouldn't?

I think if the asterisk would be restricted to digits this should be quite safe. Or phrased the other way round: if one names a file `tst/pkgname[digits].tst` AutoDoc might overwrite it anyway.

**Comment by fingolfin** [comment]
@zickgraf I misread the code and thought there could be other things that digits, but upon revisiting it, I think you are right :-). Thanks!

**Comment by fingolfin** [comment]
Proposed fix in PR #245, reviews welcome (it seems to work in some manually performed tests, but I have not yet tried to test it as part of the CI)
