### ISSUE TITLE
Resolve FIXMEs in AutoDoc()

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#56]
The FIXMEs introduced by b8b9aa09b should be resolved. 

- [x] The  first one introduces a weird entry to the index that seems to serve no purpose.

- [ ] The next one creates an DocumentationTree() object unconditionally. But shouldn't that only be created (and used!) if using AutoDoc mode, i.e. if "autodoc" is bound? Note that the tree object is later on also used later in code that is run even if autodoc is not bound (e.g. if is_worksheet is true or if scaffold.TitlePage is bound).

- [ ] The third issue is similar... It seems that maybe if "is_worksheet" is set to true, then autodoc and scaffold mode are implied. But this is not mentioned anywhere, nor checked nor enforced by the code. Thus if a user should forget to do that, they would get strange, not-helpful errors.

**Comment by fingolfin** [comment]
I really wonder about this self-entry of the book into the index. The only explanation I could come up with is that this might be there to prevent an error (?) if the index is otherwise empty?

**Comment by sebasguts** [comment]
So, I could not trigger an error if this part is missing. Maybe it is there for convenience, so that you could write &Bookname; in the manual without having to specify?

**Comment by fingolfin** [comment]
Huh? But I can do that anyway -- there is no need for the entity to be an entry in the *index* for that, is there?

**Comment by sebasguts** [comment]
Okay, then I see no need for this.

**Comment by sebasguts** [comment]
Why did this commit message close the issue? It just said part of #56 ? Does every reference closes issues?

**Comment by fingolfin** [comment]
That was the commit message of the pull request -- which is automatically based on the title of the pull request. I was sloppy and didn't pay attention, and thus failed to notice that it still contained "closes #56".

**Comment by fingolfin** [comment]
The first of the three FIXMEs was resolved. But this remains in `Magic.gi`, line 380, and I really wonder about it.
> # FIXME: We use scaffold and autodoc here without checking whether
> # they are bound. Does that mean worksheets always use them?

**Comment by fingolfin** [comment]
No point tracking FIXME comments in an issue...
