### ISSUE TITLE
Use amsmath package

### ISSUE THREAD

**Issue by sebasguts** [gap-packages/AutoDoc#72]
Maybe add the amsmath package to the LaTeX-Header. This could also be done in GAPDoc, so maybe ask Frank about it.

**Comment by fingolfin** [comment]
Didn't you implement something like this at some point? If so, is it documented?

**Comment by sebasguts** [comment]
There are the ```latex_header_file``` and the ```gapdoc_latex_options``` as values for the scaffold record. Probably, they should be in the ```gapdoc``` record, but both of them could be used to achieve this. Unfortunately, it is not as easy as it could be. Maybe we could simply have a header option?

**Comment by fingolfin** [comment]
You mean a header option to do ... what? Switch on use amsmath? Or something more generic? If so, what? I..e what do the two option you already do, exactly?

**Comment by sebasguts** [comment]
No, they do not switch on amsmath directly. The option ```gapdoc_latex_options``` passes its value to ```SetGAPDoc2LaTeXOptions```, which means you can for example write
```
[ "EarlyExtraPreamble", "\\usepackage{amsmath}" ]
```
this to have amsmath included. The GAPDoc manual is not really clear about what *can* be done using this option, but you can actually adjust most of the stuff you need here.

```latex_header_file``` is a bit more delicate. It will replace the whole GAPDoc Latex header with the file you have given in the path. To get some nice output, you basically need to copy the file, and adjust it where you want to.

Needless to say, those possibilities are actually not the best ways to do this, but maybe they can be made easier to use by another option?

**Comment by mohamed-barakat** [comment]
I remember struggling for two hours to use amsart with no success.

**Comment by sebasguts** [comment]
I think this was done for #55 and I think specially for this problem. I also think it worked for something.

**Comment by fingolfin** [comment]
Several packages now use `LateExtraPreamble` in their `makedoc.g` file successfully to use `amsmath` and other packages. So I think we are covered here.
