### ISSUE TITLE
Better error messages 

### ISSUE THREAD

**Issue by sebasguts** [gap-packages/AutoDoc#79]
Create error messages that are useful.

**Comment by fingolfin** [comment]
So the error I mentioned above now is handled much nicer.

I am tempted to close this issue, as it is very vague. What are the errors that are supposed to become better? If you tell me that, I can work on them, but right now, I don't know what they are. But if you become aware of "bad errors", I think it makes more sense to open separate issues for each of them, so we can track our progress on handling them.
