### ISSUE TITLE
Headings for groups

### ISSUE THREAD

**Issue by oysteins** [gap-packages/AutoDoc#90]
Can I specify the heading for a group in AutoDoc?

I have observed that if I create a group in AutoDoc using @BeginGroup and @EndGroup, then in the generated GAPDoc code, there is a single ManSection element containing all functions in the group, but with no Heading element.  GAPDoc then uses the name of the first function in the ManSection as heading for the section.  This is not always what I want.  My question is thus: Can I somehow get AutoDoc to insert a Heading element in the ManSection it generates for a group, containing some arbitrary text specified by me?

**Comment by fingolfin** [comment]
@sebasguts Can you answer this?

**Comment by sebasguts** [comment]
Currently this is not possible, but I noticed that GAPDoc is able to support this. Would it be a good idea to have a ```@GroupHead``` command for this? Maybe one does not want to have the name of the group inserted by default?

**Comment by oysteins** [comment]
Yes, a `@GroupHead` command (which takes some text as argument and generates a `Heading` element containing this text) would resolve the issue.  Sorry for the very late reply.
