### ISSUE TITLE
AutoDoc broken by immutifying of gap standard library

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/AutoDoc#92]
In the current git head of gap, a change has been made to make PackageInfo Immutable.

This breaks autodoc, because magic.gi:109 makes a copy of the package info, like this:

`package_info := PackageInfo( pkg )[ 1 ];`

And then, later tries to add more information to this copy.

Technically, this was always naughty, what this is showing is that autodoc was injecting new members into the global PackageInfo structure, but now it doesn't work.

Unfortunately GAP doesn't seem to have a nice "make deep mutable copy" function.

**Comment by ChrisJefferson** [comment]
Woops, actually fixed in git head!

**Comment by fingolfin** [comment]
Yeah, I run into this issue and fixed it when we were in Trondheim. But I guess a proper new AutoDoc release must be made so that this fix makes it into the next GAP release...

**Comment by sebasguts** [comment]
I will do the release today or tomorrow, I think. After that, I will make the tar.gz file to be downloaded from github, so that everyone can make a new release :)
