### ISSUE TITLE
Remove compat.gi

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#94]
I am currently cleaning up the AutoDoc code. **After** that is done (please not before!), we may consider removing `compat.gi`. As far as I can tell, no package is using this old stuff anymore.

**Comment by sebasguts** [comment]
I do not think that any package is still using it. If so, it would be some homalg package. But I also have a script converting from the old syntax to the new, so if necessary, I could convert some packages really fast.

**Comment by fingolfin** [comment]
Well, I grepped for `WithDoc` in `homalg_project` before submitting this issue. The only hit I found was this line in `ToricVarieties/gap/GroebnerBasisOfToricIdeal.gd:11`, which is commented out:
```
# DeclareOperationWithDocumentation( "GeneratingSetOfToricIdealGivenByHilbertBasis",
```

But I just noticed that I forgot about `homalg_project_extensions. There are still users there, namely in the `Orbifolds` and `AlgebraicThomas` packages. Hrm.

**Comment by sebasguts** [comment]
I just updated `AlgebraicThomas`, Orbifolds might take some more time, since there is mixed GAPDoc and AutoDoc code, but this will be done soon.

Please do not look at the `homalg_project_extensions`. We decided on not using a single repository for the unsubmitted packages, so this might not be up-to-date.

**Comment by fingolfin** [comment]
I don't see any update for `AlgebraicThomas`, did you push it?

Also, why does `homalg_project_extensions` exist then? If it is stale, shouldn't you just remove it, to avoid misleading people like me? :)

**Comment by fingolfin** [comment]
And I wanted to log an issue with `Orbifolds` to make sure we don't forget, but it has no issue tracker. Is that intentional? Maybe @mohamed-barakat had a reason for that?

**Comment by mohamed-barakat** [comment]
Please feel free to take draconic measures :+1:
