### ISSUE TITLE
Document worksheets, in particular AutoDocWorksheet

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/AutoDoc#95]
The whole worksheet business is currently undocumented. Please fix that.

In particular, I would like to refacto the code in `gap/Magic.gi`, to make it less of a hack, and make it clearer which bits are used for worksheets, which for packages, and which for both.

But I cannot really do that, as I don't know what is supposed to work and how; so if I find some weird edge behavior of code, I have no way of knowing whether it is intentional, or a bug, or perhaps a case of "used to be intentional but now we don't use it anymore".

As a minor first step, I just opened sebasguts/AutoDocTestPackage#5 which at least adds a single test worksheet (one that @sebasguts once sent me)

**Comment by fingolfin** [comment]
Some of the weird things:
* it seems that the worksheet code implicitly assumes both `autodoc` and `scaffold` options are set. But looking at it, `AutoDocWorksheet` can be called with no arguments, and then `autodoc` may not be set
* there is code which computes a `pkgname` value for worksheets if no `TitlePage` resp. `Title` info can be found. But I just tried a worksheet without a title, and that results in an error anyway. So perhaps that code can just be removed?
* later in the code, we do this: `CreateMainPage( pkgname, doc_dir, scaffold );` -- this is a bit weird, since the first parameter really should be the bookname. I think this really should be using `gapdoc.bookname` -- but I am afraid this might break worksheets... Anyway, I am going to do that anyway for now, and will wait for you to complain if necessary :)

**Comment by fingolfin** [comment]
I just realized that I documented some of that already in issue #56 -- but I should have made clear there that @sebasguts will have to resolve it, as I think he added that code, and I don't dare touch it without knowing more about what it is good for.

**Comment by sebasguts** [comment]
The worksheet functionally is ATM kind of a hack. I am trying to rearrange some stuff in the AutoDoc method to see the difference. Also, right now, there is not really a standard for worksheets. So, I am going to rearrange some code, to have the shared code of `AutoDoc()` and `AutoDocWorksheet()` a bit more seperated from the two methods, and to make it completely clear what is possible with the worksheets and what is not.

Right now, there are several hacks in `AutoDoc()` for the worksheets. I can hopefully remove all of those, once I am done with this :).
